# GENERAL ==============================
warning = { fg = "warn_yellow" }
error = { fg = "error_red" }
diagnostic = { modifiers = ["underlined"] }
info = { fg = "blue_alt" }
hint = { fg = "green_alt" }

# UI ==============================
"ui.background" = { bg = "bg", fg = "fg" }
"ui.text" = { fg = "fg" }
"ui.help" = { bg = "bg_dim", fg = "fg" }
"ui.window" = { fg = "window_edge" }
"ui.popup" = { bg = "bg_dim", fg = "fg" }
"ui.menu" = { bg = "bg_dim", fg = "fg" }
"ui.menu.selected" = { bg = "bg_hover" }
"ui.statusline" = { fg = "fg" }
"ui.linenr" = { fg = "gutter" }
"ui.linenr.selected" = { fg = "fg" }
"ui.virtual" = { fg = "fg_dim", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "ruler" }
"ui.virtual.whitespace" = { fg = "ruler" }
"ui.selection" = { bg = "sel" }
"ui.selection.primary" = { bg = "sel" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "green", modifiers = ["underlined", "bold"] }
"ui.cursorline.primary" = { bg = "bg_dim" }

# SYNTAX HIGHLIGHTING ==============================
"comment" = { fg = "muted", modifiers = ["italic"] }
"constant" = { fg = "blue" }
"constant.character.escape" = { fg = "blue_alt" }
"function" = { fg = "purple" }
"function.macro" = { }
"keyword" = { fg = "keyword_red" }
"operator" = { fg = "blue" }
"string" = { fg = "blue_alt" }
"string.regexp" = { fg = "blue_alt" }
"type" = { fg = "orange" }
"tag" = { fg = "green" }
"special" = { fg = "purple" }

# MARKUP ========================================
"markup.bold" = { fg = "fg", modifiers = ["bold"] }
"markup.italic" = { fg = "fg", modifiers = ["italic"] }
"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.link" = { fg = "blue_alt", modifiers = ["underline"] }
"markup.quote" = { fg = "green_alt" }
"markup.raw" = { fg = "blue" }

[palette]
bg = "#0d1117"
bg_dim = "#010409"
bg_hover = "#161b22"
sel = "#3c4a5d"
fg = "#c9d1d9"
fg_dim = "#5d626e"
muted = "#8b949e"
gutter = "#6e7681"
ruler = "#484f58"
blue = "#79c0ff"
blue_alt = "#a5d6ff"
purple = "#bc8cff"
green = "#2ea043"
green_alt = "#7ee787"
orange = "#ffa657"
keyword_red = "#ff7b72"
error_red = "#ffa198"
warn_yellow = "#d29922"
window_edge = "#0d1117"
