theme = "github_dark"

[editor]
true-color = true
line-number = "relative"
mouse = false
default-yank-register = "+"
clipboard-provider = "wayland"
end-of-line-diagnostics = "hint"
bufferline = "multiple"
completion-trigger-len = 1
completion-timeout = 5
completion-replace = true

# [editor.clipboard-provider.custom]
# yank = { command = "clipse", args = ["-a"] }
# paste = { command = "clipse", args = ["-p"] }

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = "⏎"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = [
  "diagnostics",
  "version-control",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-s = ":write!"
C-x = ":reset-diff-change"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
W = 'move_next_sub_word_start'
B = 'move_prev_sub_word_start'
E = 'move_next_sub_word_end'

[keys.normal.space]
space = "file_picker"

[keys.normal.space.b]
f = "buffer_picker"
q = ":buffer-close"
o = ":buffer-close-others"
s = ":write-buffer-close"

[keys.normal.space.q]
q = ":quit-all"
s = ":write-quit-all!"
f = ":quit-all!"

[keys.normal.space.c]
f = ":format"
d = ["extend_to_line_bounds", "yank", "paste_after"]
u = ["extend_to_line_bounds", "yank", "paste_before"]

[keys.insert]
j = { j = "normal_mode" }
C-l = "move_char_right"

[keys.select]
W = 'extend_next_sub_word_start'
B = 'extend_prev_sub_word_start'
E = 'extend_next_sub_word_end'
