[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "html"
formatter = { command = "superhtml", args = ["fmt", "-"] }

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
formatter = ["gofmt"]

# [language-server.plz-lsp]
# command = "plz"
# args = ["tool", "lps"]

# [[language]]
# name = "plz"
# scope = "source.plz"
# file-types = ["plz", { glob = "BUILD" }]
# roots = [".plzconfig"]
# language-servers = ["plz-lsp"]

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "dockerfile"
language-servers = ["docker-lsp"]

[[language]]
name = "docker-compose"
language-servers = ["docker-lsp", "yaml-language-server"]

[language-server.docker-lsp]
command = "docker-language-server"
args = ["start"]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
